#!/bin/bash 

# https://osf.io/axz5r/

cd /Volumes/xyu
rest:
curl -L --retry 10 --retry-delay 5 -o rest.zip "https://files.osf.io/v1/resources/axz5r/providers/osfstorage/5cb62136f2be3c0017077a5a/?zip="

dti:
curl -L --retry 10 --retry-delay 5 -o dti.zip "https://files.osf.io/v1/resources/axz5r/providers/osfstorage/5cb0be5c353c58001c98fb2a/?zip="

t1:
curl -L --retry 10 --retry-delay 5 -o t1.zip "https://files.osf.io/v1/resources/axz5r/providers/osfstorage/5dcc8693360e17000ba10666/?zip="